# Generated by Django 3.0.8 on 2020-07-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='hvac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hvac.Hvac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='hvac_webid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
